# Generated by Django 3.1.5 on 2021-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='offer',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
