# Generated by Django 3.1.5 on 2021-02-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210201_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestbid',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
